# 예외처리

## try catch finally

문자열을 매개변수로 받아 정수로 변환하는 예제를 작성해보려 한다.

```java
// Java
private int parseIntOrThrow(@NotNull String str) {
    try {
        return Integer.parseInt(str);
    } catch (NumberFormatException e) {
        throw new IllegalArgumentException(String.format("주어진 %s는 숫자가 아닙니다.", str));
    }    
}
```

```kotlin
// Kotlin
fun parseIntOrThrow(str: String): Int {
    try {
        return str.toInt()
    } catch (e: NumberFormatException) {
        throw IllegalArgumentException("주어진 ${str}는 숫자가 아닙니다.")
    }
}
```

위의 자바와 코틀린 코드의 차이점은 아래와 같다.
 - 기본 타입간의 형변환은 toType()을 사용한다.
 - 타입이 뒤에 위치하고 new를 사용하지 않는다.

하지만 try-catch 구문의 문법은 동일하다.


다음 예제는 주어진 문자열을 정수로 변경하는 예제로 실패하면 null을 반환한다.
```java
// Java
private int parseIntOrThrowV2(@NotNull String str) {
    try {
        return Integer.parseInt(str);
    } catch (NumberFormatException e) {
        return null;
    }    
}
```

```kotlin
// Kotlin
fun parseIntOrThrowV2(str: String): Int? {
    return try {
        str.toInt()
    } catch (e: NumberFormatException) {
        null
    }
}
```

코틀린에서 try-catch문은 자바와 달리 `Statement`가 아닌 `Expression`이다. 때문에 위 코드와 같이 try-catch문을 return하여 결과를 출력할 수 있다.
(코틀린의 조건문 또한 `Expression`이기 때문에 위와 같이 return 하여 표현할 수 있다.)

## Checked Exception과 Unchecked Exception

이제 프로젝트 내 파일을 읽어오는 예제를 자바코드와 코틀린 코드로 작성해보겠다.

```java
// Java
public void readFile() throws IOException {
    File currentFile = new File(".");
    File file = new File(currentFile.getAbsolutePath() + "/a.txt");
    BufferedReader reader = new BufferedReader(new FileReader(file));
    System.out.println(reader.readLine());
    reader.close();
}
```

```kotlin
// Kotlin
fun readFile() {
    val currentFile = File(".")
    val file = File(currentFile.absolutePath + "/a.txt")
    val reader = BufferedReader(FileReader(file))
    println(reader.readLine())
    reader.close()
}
```

위 코드에서 가장 큰 차이점은 `IOException`의 throws 여부이다. 자바에서 `IOException`은 `Checked Exception`으로 try-catch문이나 throws를 통해 예외를 처리해 주어야한다.
하지만 코틀린에서는 `Checked Exception`과 `Unchecked Exception`을 구분하지 않고 모두 `Unchecked Exception`으로 사용된다.

## Checked Exception vs Unchecked Exception
Exception은 `Checked Exception`과 `Unchecked Exception`으로 구분할 수 있는데,
간단하게 `RuntimeException`을 상속하지 않는 클래스는 `Checked Exception`, 반대로 상속한 클래스는 `Unchecked Exception`으로 분류할 수 있다.

## try with resources

이제 위 코드들을 try-with-resources 구문을 사용하여 표현해보자.
```java
public void readFile(String path) throws IOException {
    try (BufferedReader reader = new BufferedReader(new FileReader(path))) {
        System.out.println(reader.readLine());
    }
}
```

JDK7에서 추가된 try-with-resources는 위와 같이 try문에서 사용할 resource를 명시하고
try문이 끝나면 자동으로 resource를 close한다.


코틀린의 경우는 try-with-resources 구문을 지원하지 않는다. 하지만 아래와 같이 코틀린은 `use` 메서드를 활용하여 같은 효과를 낼수있다. 
```kotlin
fun readFile(path: String) {
    BufferedReader(FileReader(path)).use { reader ->
        println(reader.readLine())
    }
}
```
